import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
// import { SocketContextProvider } from "@/Socket/socketContext";
import React from "react";
import DesktopNavbar from "@/components/navbar/DesktopNavbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        {/* <SocketContextProvider> */}
        {/* <DesktopNavbar /> */}
        <body className={inter.className}>{children}</body>
        {/* </SocketContextProvider> */}
      </Providers>
    </html>
  );
}
