import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import Navbar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <Providers>
        {/* <SocketContextProvider> */}
        <body
          className={`${inter.className} dark:bg-slate-800 transition-colors duration-300`}
        >
          <Navbar />
          {children}
        </body>
        {/* </SocketContextProvider> */}
      </Providers>
    </html>
  );
}
